### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by mirandrom** [nlgknowledge/commonsense#1]
Hello, I really enjoyed your talk at EACL 2021 today. 
Just a heads up, the link in your repo's About section (commonsense.github.io) is broken and should probably be https://nlgknowledge.github.io/commonsense/

**Comment by MirunaClinciu** [comment]
Hi, 
I am glad to hear that you enjoyed the talk! Please feel free to contact us if you need any further information.
Also, thank you very much for letting us know about this issue. Now, I updated the link in the About section too.
